# Configuration file for Kres
#
# Kres configuration is a multi-document YAML file, each document has same structure:
#
#   ---
#   kind: <package>.<Type>
#   name: <nodeName>  # (optional)
#   spec:  # configuration for specific project node
#      field: value
#      ...
#
#
# Any node in the tree might have its configuration overridden via the config.

---
kind: common.Image
name: image-kres
spec:
    entrypointArgs: ['gen']

---
kind: service.CodeCov
spec:
    targetThreshold: 10
---
kind: common.Build
spec:
    ignoredPaths:
        - "_out/example/"
---
kind: golang.Generate
spec:
    versionPackagePath: internal/version
