name: default
"on":
  push:
    branches:
      - main
    tags:
      - v*
  pull_request_target: {}
env:
  CI_ARGS: --cache-from=type=registry,ref=registry.ci.svc.cluster.local:5000/${GITHUB_REPOSITORY}:buildcache --cache-to=type=registry,ref=registry.ci.svc.cluster.local:5000/${GITHUB_REPOSITORY}:buildcache,mode=max
jobs:
  default:
    permissions:
      contents: write
      packages: write
    runs-on: [self-hosted,X64]
    if: github.event_name != 'pull_request_target' || contains(github.event.pull_request.labels.*.name, 'status/ok-to-test')
    steps:
      - name: checkout
        uses: actions/checkout@v3
