name: default
"on":
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
env:
  CI_ARGS: --cache-from=type=registry,ref=registry.ci.svc.cluster.local:5000/${GITHUB_REPOSITORY}:buildcache --cache-to=type=registry,ref=registry.ci.svc.cluster.local:5000/${GITHUB_REPOSITORY}:buildcache,mode=max
jobs:
  default:
    permissions:
      contents: write
      packages: write
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v3
